CREATE TABLE address (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   country VARCHAR(255),
   region VARCHAR(255),
   city VARCHAR(255),
   code BIGINT,
   other VARCHAR(255),
   order_number VARCHAR(255),
   CONSTRAINT pk_address PRIMARY KEY (id)
);

ALTER TABLE address ADD CONSTRAINT uc_address_ordernumber UNIQUE (order_number);

INSERT
INTO
  address
  (country, region, city, code, other, order_number)
VALUES
  ('Deutschland', 'NRW', 'Düsseldorf', 40225, '', 'ORDERNUM1');